### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by danielmlow** [danielmlow/construct-tracker#2]
# ToDos

- [ ] `lexicon.extract` should output a columns called `document_n` and `document_str`
- [ ] `lexicon.add` clean up how I store metadata automatically and manually. Maybe create a brief input() dialogue so it saves user, timestamp, source, etc. 
- [ ] `Clean up output for `matches_per_construct` `matches_counter_d` and `matches_per_doc`?
- [ ] Add CTS
- [ ] Add additional arguments for CTS
